In [1]:
ls -l ../

total 4
drwxrwxr-x. 2 sac086 sac086 4096 Nov  2 11:33 data/
drwxrwxr-x. 2 sac086 sac086   32 Nov  2 11:35 extrasense/
drwxrwxr-x. 3 sac086 sac086   62 Nov  2 12:15 notebooks/


In [2]:
ls -l ../data

total 26335396
-rw-rw-r--. 1 sac086 sac086      10803 May 18 16:46 cv5Folds.zip
-rw-rw-r--. 1 sac086 sac086    2303359 May 23 15:23 ExtraSensory.per_uuid_absolute_location.zip
-rw-rw-r--. 1 sac086 sac086  225374973 May 23 15:22 ExtraSensory.per_uuid_features_labels.zip
-rw-rw-r--. 1 sac086 sac086     813701 Jul 20 12:15 ExtraSensory.per_uuid_mood_labels.zip
-rw-rw-r--. 1 sac086 sac086     992570 May 23 15:23 ExtraSensory.per_uuid_original_labels.zip
-rw-rw-r--. 1 sac086 sac086 9999131024 Jul 20 23:46 ExtraSensory.raw_measurements.proc_gravity.zip
-rw-rw-r--. 1 sac086 sac086 9333898324 Jul 20 17:00 ExtraSensory.raw_measurements.proc_gyro.zip
-rw-rw-r--. 1 sac086 sac086 6475399720 Jul 20 14:54 ExtraSensory.raw_measurements.raw_acc.zip
-rw-rw-r--. 1 sac086 sac086  837898335 Jun 20 09:34 ExtraSensory.raw_measurements.watch_acc.zip
-rw-rw-r--. 1 sac086 sac086   91596286 Jun 20 11:22 ExtraSensory.raw_measurements.watch_compass.zip


In [13]:
ls -l ../data/features_labels/ 

total 765672
-rw-rw-r--. 1 sac086 sac086  4524514 May 15 17:14 00EABED2-271D-49D8-B599-1D4A09240601.features_labels.csv
-rw-rw-r--. 1 sac086 sac086 13676286 May 15 17:13 098A72A5-E3E5-4F54-A152-BBDA0DF7B694.features_labels.csv
-rw-rw-r--. 1 sac086 sac086  8554303 May 15 17:17 0A986513-7828-4D53-AA1F-E02D6DF9561B.features_labels.csv
-rw-rw-r--. 1 sac086 sac086  6715529 May 15 17:15 0BFC35E2-4817-4865-BFA7-764742302A2D.features_labels.csv
-rw-rw-r--. 1 sac086 sac086 15584869 May 15 17:16 0E6184E1-90C0-48EE-B25A-F1ECB7B9714E.features_labels.csv
-rw-rw-r--. 1 sac086 sac086  5594569 May 15 17:17 1155FF54-63D3-4AB2-9863-8385D0BD0A13.features_labels.csv
-rw-rw-r--. 1 sac086 sac086 19245303 May 15 17:13 11B5EC4D-4133-4289-B475-4E737182A406.features_labels.csv
-rw-rw-r--. 1 sac086 sac086 13690862 May 15 17:13 136562B6-95B2-483D-88DC-065F28409FD2.features_labels.csv
-rw-rw-r--. 1 sac086 sac086 12706378 May 15 17:15 1538C99F-BA1E-4EFB-A949-6C7C47701B20.features_labels.csv
-rw-rw-r--. 1 sac086 sac

In [7]:
import pandas as pd

In [15]:
features_df = pd.read_csv("../data/features_labels/00EABED2-271D-49D8-B599-1D4A09240601.features_labels.csv")

In [17]:
features_df.head()

timestamp  raw_acc:magnitude_stats:mean  raw_acc:magnitude_stats:std  \
0  1444079161                      0.996815                     0.003529   
1  1444079221                      0.996864                     0.004172   
2  1444079281                      0.996825                     0.003667   
3  1444079341                      0.996874                     0.003541   
4  1444079431                      0.997371                     0.037653   

   raw_acc:magnitude_stats:moment3  raw_acc:magnitude_stats:moment4  \
0                        -0.002786                         0.006496   
1                        -0.003110                         0.007050   
2                         0.003094                         0.006076   
3                         0.000626                         0.006059   
4                         0.043389                         0.102332   

   raw_acc:magnitude_stats:percentile25  raw_acc:magnitude_stats:percentile50  \
0                              0.995203                              0.996825   
1                              0.994957                              0.996981   
2                              0.994797                              0.996614   
3                              0.995050                              0.996907   
4                              0.995548                              0.996860   

   raw_acc:magnitude_stats:percentile75  \
0                              0.998502   
1                              0.998766   
2                              0.998704   
3                              0.998690   
4                              0.998205   

   raw_acc:magnitude_stats:value_entropy  \
0                               1.748756   
1                               1.935573   
2                               2.031780   
3                               1.865318   
4                               0.460806   

   raw_acc:magnitude_stats:time_entropy      ...       \
0                              6.684605      ...        
1                              6.684603      ...        
2                              6.684605      ...        
3                              6.684605      ...        
4                              6.683904      ...        

   label:STAIRS_-_GOING_DOWN  label:ELEVATOR  label:OR_standing  \
0                        NaN             NaN                0.0   
1                        NaN             NaN                0.0   
2                        NaN             NaN                0.0   
3                        NaN             NaN                0.0   
4                        NaN             NaN                0.0   

   label:AT_SCHOOL  label:PHONE_IN_HAND  label:PHONE_IN_BAG  \
0              NaN                  NaN                 NaN   
1              NaN                  NaN                 NaN   
2              NaN                  NaN                 NaN   
3              NaN                  NaN                 NaN   
4              NaN                  NaN                 NaN   

   label:PHONE_ON_TABLE  label:WITH_CO-WORKERS  label:WITH_FRIENDS  \
0                   1.0                    1.0                 NaN   
1                   1.0                    1.0                 NaN   
2                   1.0                    1.0                 NaN   
3                   1.0                    1.0                 NaN   
4                   1.0                    1.0                 NaN   

   label_source  
0             2  
1             2  
2             2  
3             2  
4             2  

[5 rows x 278 columns]

In [20]:
for ind, col in enumerate(features_df.columns):
    print("%s : %s" % (ind, col))

0 : timestamp
1 : raw_acc:magnitude_stats:mean
2 : raw_acc:magnitude_stats:std
3 : raw_acc:magnitude_stats:moment3
4 : raw_acc:magnitude_stats:moment4
5 : raw_acc:magnitude_stats:percentile25
6 : raw_acc:magnitude_stats:percentile50
7 : raw_acc:magnitude_stats:percentile75
8 : raw_acc:magnitude_stats:value_entropy
9 : raw_acc:magnitude_stats:time_entropy
10 : raw_acc:magnitude_spectrum:log_energy_band0
11 : raw_acc:magnitude_spectrum:log_energy_band1
12 : raw_acc:magnitude_spectrum:log_energy_band2
13 : raw_acc:magnitude_spectrum:log_energy_band3
14 : raw_acc:magnitude_spectrum:log_energy_band4
15 : raw_acc:magnitude_spectrum:spectral_entropy
16 : raw_acc:magnitude_autocorrelation:period
17 : raw_acc:magnitude_autocorrelation:normalized_ac
18 : raw_acc:3d:mean_x
19 : raw_acc:3d:mean_y
20 : raw_acc:3d:mean_z
21 : raw_acc:3d:std_x
22 : raw_acc:3d:std_y
23 : raw_acc:3d:std_z
24 : raw_acc:3d:ro_xy
25 : raw_acc:3d:ro_xz
26 : raw_acc:3d:ro_yz
27 : proc_gyro:magnitude_stats:mean
28 : proc_gyr

In [28]:
acc_col_name = [col for col in features_df.columns if "raw_acc" in col]
acc_col_name

['raw_acc:magnitude_stats:mean',
 'raw_acc:magnitude_stats:std',
 'raw_acc:magnitude_stats:moment3',
 'raw_acc:magnitude_stats:moment4',
 'raw_acc:magnitude_stats:percentile25',
 'raw_acc:magnitude_stats:percentile50',
 'raw_acc:magnitude_stats:percentile75',
 'raw_acc:magnitude_stats:value_entropy',
 'raw_acc:magnitude_stats:time_entropy',
 'raw_acc:magnitude_spectrum:log_energy_band0',
 'raw_acc:magnitude_spectrum:log_energy_band1',
 'raw_acc:magnitude_spectrum:log_energy_band2',
 'raw_acc:magnitude_spectrum:log_energy_band3',
 'raw_acc:magnitude_spectrum:log_energy_band4',
 'raw_acc:magnitude_spectrum:spectral_entropy',
 'raw_acc:magnitude_autocorrelation:period',
 'raw_acc:magnitude_autocorrelation:normalized_ac',
 'raw_acc:3d:mean_x',
 'raw_acc:3d:mean_y',
 'raw_acc:3d:mean_z',
 'raw_acc:3d:std_x',
 'raw_acc:3d:std_y',
 'raw_acc:3d:std_z',
 'raw_acc:3d:ro_xy',
 'raw_acc:3d:ro_xz',
 'raw_acc:3d:ro_yz']

In [29]:
gyro_col_name = [col for col in features_df.columns if "gyro" in col]
gyro_col_name

['proc_gyro:magnitude_stats:mean',
 'proc_gyro:magnitude_stats:std',
 'proc_gyro:magnitude_stats:moment3',
 'proc_gyro:magnitude_stats:moment4',
 'proc_gyro:magnitude_stats:percentile25',
 'proc_gyro:magnitude_stats:percentile50',
 'proc_gyro:magnitude_stats:percentile75',
 'proc_gyro:magnitude_stats:value_entropy',
 'proc_gyro:magnitude_stats:time_entropy',
 'proc_gyro:magnitude_spectrum:log_energy_band0',
 'proc_gyro:magnitude_spectrum:log_energy_band1',
 'proc_gyro:magnitude_spectrum:log_energy_band2',
 'proc_gyro:magnitude_spectrum:log_energy_band3',
 'proc_gyro:magnitude_spectrum:log_energy_band4',
 'proc_gyro:magnitude_spectrum:spectral_entropy',
 'proc_gyro:magnitude_autocorrelation:period',
 'proc_gyro:magnitude_autocorrelation:normalized_ac',
 'proc_gyro:3d:mean_x',
 'proc_gyro:3d:mean_y',
 'proc_gyro:3d:mean_z',
 'proc_gyro:3d:std_x',
 'proc_gyro:3d:std_y',
 'proc_gyro:3d:std_z',
 'proc_gyro:3d:ro_xy',
 'proc_gyro:3d:ro_xz',
 'proc_gyro:3d:ro_yz']

In [30]:
label_col_name = [col for col in features_df.columns if "label" in col]
label_col_name

['label:LYING_DOWN',
 'label:SITTING',
 'label:FIX_walking',
 'label:FIX_running',
 'label:BICYCLING',
 'label:SLEEPING',
 'label:LAB_WORK',
 'label:IN_CLASS',
 'label:IN_A_MEETING',
 'label:LOC_main_workplace',
 'label:OR_indoors',
 'label:OR_outside',
 'label:IN_A_CAR',
 'label:ON_A_BUS',
 'label:DRIVE_-_I_M_THE_DRIVER',
 'label:DRIVE_-_I_M_A_PASSENGER',
 'label:LOC_home',
 'label:FIX_restaurant',
 'label:PHONE_IN_POCKET',
 'label:OR_exercise',
 'label:COOKING',
 'label:SHOPPING',
 'label:STROLLING',
 'label:DRINKING__ALCOHOL_',
 'label:BATHING_-_SHOWER',
 'label:CLEANING',
 'label:DOING_LAUNDRY',
 'label:WASHING_DISHES',
 'label:WATCHING_TV',
 'label:SURFING_THE_INTERNET',
 'label:AT_A_PARTY',
 'label:AT_A_BAR',
 'label:LOC_beach',
 'label:SINGING',
 'label:TALKING',
 'label:COMPUTER_WORK',
 'label:EATING',
 'label:TOILET',
 'label:GROOMING',
 'label:DRESSING',
 'label:AT_THE_GYM',
 'label:STAIRS_-_GOING_UP',
 'label:STAIRS_-_GOING_DOWN',
 'label:ELEVATOR',
 'label:OR_standing',
 'l

In [32]:
activity_labels_name = ["label:LYING_DOWN", 'label:SITTING', 'label:STAIRS_-_GOING_UP', 
                        'label:STAIRS_-_GOING_DOWN', 'label:FIX_walking', 'label:FIX_running',
                        'label:BICYCLING',]

In [39]:
acc_features_df = features_df[features_df.columns.intersection(acc_col_name)]
acc_labels_df = features_df[features_df.columns.intersection(activity_labels_name)]

In [40]:
acc_features_df.head()

raw_acc:magnitude_stats:mean  raw_acc:magnitude_stats:std  \
0                      0.996815                     0.003529   
1                      0.996864                     0.004172   
2                      0.996825                     0.003667   
3                      0.996874                     0.003541   
4                      0.997371                     0.037653   

   raw_acc:magnitude_stats:moment3  raw_acc:magnitude_stats:moment4  \
0                        -0.002786                         0.006496   
1                        -0.003110                         0.007050   
2                         0.003094                         0.006076   
3                         0.000626                         0.006059   
4                         0.043389                         0.102332   

   raw_acc:magnitude_stats:percentile25  raw_acc:magnitude_stats:percentile50  \
0                              0.995203                              0.996825   
1                              0.994957                              0.996981   
2                              0.994797                              0.996614   
3                              0.995050                              0.996907   
4                              0.995548                              0.996860   

   raw_acc:magnitude_stats:percentile75  \
0                              0.998502   
1                              0.998766   
2                              0.998704   
3                              0.998690   
4                              0.998205   

   raw_acc:magnitude_stats:value_entropy  \
0                               1.748756   
1                               1.935573   
2                               2.031780   
3                               1.865318   
4                               0.460806   

   raw_acc:magnitude_stats:time_entropy  \
0                              6.684605   
1                              6.684603   
2                              6.684605   
3                              6.684605   
4                              6.683904   

   raw_acc:magnitude_spectrum:log_energy_band0        ...         \
0                                     5.043970        ...          
1                                     5.043367        ...          
2                                     5.043599        ...          
3                                     5.043263        ...          
4                                     5.042779        ...          

   raw_acc:magnitude_autocorrelation:normalized_ac  raw_acc:3d:mean_x  \
0                                         0.148988           0.002331   
1                                         0.207046           0.003557   
2                                         0.186961           0.004180   
3                                         0.479430           0.004179   
4                                         0.202305          -0.008383   

   raw_acc:3d:mean_y  raw_acc:3d:mean_z  raw_acc:3d:std_x  raw_acc:3d:std_y  \
0           0.004614          -0.996790          0.003269          0.003521   
1           0.005495          -0.996832          0.002489          0.003772   
2           0.005776          -0.996785          0.003567          0.004051   
3           0.005551          -0.996836          0.004202          0.002919   
4          -0.000009          -0.994184          0.074612          0.023784   

   raw_acc:3d:std_z  raw_acc:3d:ro_xy  raw_acc:3d:ro_xz  raw_acc:3d:ro_yz  
0          0.003539          0.106920          0.516842          0.255494  
1          0.004177         -0.079483          0.357748          0.036252  
2          0.003681          0.122432          0.464881          0.222375  
3          0.003559          0.308841          0.773514          0.296194  
4          0.039512         -0.187758         -0.204381          0.062696  

[5 rows x 26 columns]

In [42]:
acc_labels_df.head()

label:LYING_DOWN  label:SITTING  label:FIX_walking  label:FIX_running  \
0               0.0            1.0                0.0                NaN   
1               0.0            1.0                0.0                NaN   
2               0.0            1.0                0.0                NaN   
3               0.0            1.0                0.0                NaN   
4               0.0            1.0                0.0                NaN   

   label:BICYCLING  label:STAIRS_-_GOING_UP  label:STAIRS_-_GOING_DOWN  
0              NaN                      NaN                        NaN  
1              NaN                      NaN                        NaN  
2              NaN                      NaN                        NaN  
3              NaN                      NaN                        NaN  
4              NaN                      NaN                        NaN

In [44]:
acc_labels_df['label:STAIRS_-_GOING_DOWN'].unique()

array([ nan])

In [45]:
acc_labels_df['label:STAIRS_-_GOING_UP'].unique()

array([ nan])

In [46]:
acc_labels_df['label:BICYCLING'].unique()

array([ nan])

In [47]:
acc_labels_df['label:FIX_running'].unique()

array([ nan])

In [48]:
acc_labels_df['label:FIX_walking'].unique()

array([  0.,   1.,  nan])

# Get User IDs from file names

In [49]:
import os

In [52]:
data_dir = '../data/features_labels/'
file_names = os.listdir(data_dir)
user_ids = [fn.split(".")[0] for fn in file_names]

In [245]:
def clean_labels(labels_df):
    labels = []
    for ind, row in labels_df.iterrows():
        #print(np.argmax(row))
        max_label = np.argmax(row)
        if np.isnan(np.max(row)):
            label = max_label
        else:
            if ":" in max_label:
                label = max_label.split(":")[1]
            else:
                label=max_label
        labels.append(label)
    return pd.Series(labels)

In [163]:
def clean_activity_features(features_df):
    null_ind = []

    for ind, row in features_df.iterrows():
        if row.isnull().sum() > 0:
            null_ind.append(ind)
    return features_df.drop(features_df.index[null_ind])

In [254]:
def get_data_from_user_id(user_id, data_type=None, labeled_only=False):
    user_df = pd.read_csv(data_dir+user_id+".features_labels.csv")
    if data_type is "activity":
        features_df = user_df[user_df.columns.intersection(acc_col_name)]
        labels_df = clean_labels(user_df[user_df.columns.intersection(activity_labels_name)])
        user_df = pd.concat((features_df,labels_df), axis=1)
        user_df = activity_df.rename(columns={0:'label'})
        user_df = user_df.dropna(subset=acc_col_name)
    else:
        feature_columns = [col for col in user_df.columns if col not in label_col_name]
        features_df = user_df[user_df.columns.intersection(feature_columns)]
        labels_df = clean_labels(user_df[user_df.columns.intersection(label_col_name)])
        user_df = pd.concat((features_df,labels_df), axis=1)
        print(user_df.shape)
        user_df = user_df.rename(columns={0:'label'})
        user_df = user_df.dropna(subset=feature_columns)
    if labeled_only:
        null_mask = labels_df.notnull()
        user_df = user_df[null_mask]
    return user_df

# 1st attempt at AR modeling

In [87]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit, ShuffleSplit, KFold, StratifiedKFold
from sklearn.preprocessing import StandardScaler

In [272]:
kf = KFold(n_splits=3)

user_df = get_data_from_user_id(user_ids[0], data_type="activity", labeled_only=True)

for training_ind, test_ind in kf.split(user_df):
    train_df = user_df.iloc[training_ind]
    test_df = user_df.iloc[test_ind]
    
    train_labels = train_df.pop("label")
    test_labels = test_df.pop("label")
    
    clf = RandomForestClassifier()
    
    # standard scale training
    scaler = StandardScaler().fit(train_df)
    scaled_train_df = scaler.transform(train_df)
    scaled_test_df = scaler.transform(test_df)
    
    clf.fit(scaled_train_df, train_labels)
    
    # standard scale testing
    predictions = clf.predict(scaled_test_df)
    score = accuracy_score(test_labels, predictions)
    print(score)

/usr/lib/python3.4/site-packages/ipykernel_launcher.py:19: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


0.694459681843
0.739440482721
0.468715697036
